theme: jekyll-theme-modernist

# Site settings
title: Alexander Köb
email: nerdkram@koeb.me
description: > # this means to ignore newlines until "baseurl:"
    Rambling notes about stuff that I do or that interests me. Follow at your own risk...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://akoeb.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  akoeb

# Build settings
markdown: kramdown


timezone: Europe/Berlin
