
# Site settings
title: My Github Blog
email: nerdkram@koeb.me
description: > # this means to ignore newlines until "baseurl:"
    Welcome to the github blog of Alexander Köb, I write about things I encounter in my technical life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://akoeb.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  akoeb

# Build settings
markdown: kramdown
theme: jekyll-theme-modernist


timezone: Europe/Berlin
